services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./app:/app/app
      - ./static:/app/static
    environment:
      - DB_HOSTNAME=db
      - DB_PORT=5432
      - DB_PASSWORD=password
      - DB_NAME=mundo_persistente
      - DB_USERNAME=usuario
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mundo_persistente
      - POSTGRES_USER=usuario

volumes:
  postgres_data: