services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./app:/app/app
      - ./static:/app/static
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - DB_HOSTNAME=db
      - DB_PORT=5432
      - DB_PASSWORD=password
      - DB_NAME=mundo_persistente
      - DB_USERNAME=usuario
      - TF_CPP_MIN_LOG_LEVEL=2
      - TF_ENABLE_ONEDNN_OPTS=0
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mundo_persistente
      - POSTGRES_USER=usuario

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: